defaults:
  - _self_
  - task: os_prediction_extreme #tcga_nsclc_cancer_subtype_prediction #tcga_lusc_os_prediction #tcga_lusc_myS #dataset_prediction #tcga_nsclc_cancer_subtype_prediction 
  - model: abmil #abmil

tune_version: dino_v2_tcga_ha #dino_v2_s36_ha #dino_p_tcga_ha4 #dino2_p_tcga_ha #dino_p_tcga_ha4 #dinov2_p_tcgaunn2 #dino_tcga_10tile_100_wOrg #dino_10tile_100, dino_tcga_10tile_100, dino_tcga_10tile_100_wOrg

testing_datasets: 
  - UNN_LUSC

training_datasets:
  - S36_LUSC
  
features_root_dir: /home/vilde/data/
#features_root_dir: /home/vilde/code/Phikon
#logs_root_dir: /home/vilde/code/Phikon/HistoSSLscaling/logs_dmz_extreme_linear
logs_root_dir: /home/vilde/code/Phikon/HistoSSLscaling/logs_2