defaults:
  - _self_
  - task: tcga_lusc_os_prediction #dataset_prediction #tcga_lusc_os_prediction
  - model: abmil

tune_version: dino_p_unn_ha #dino_p_tcga_ha4 #dino_p_tcga_ha6 #dino2_p_tcga_ha #dino_p_tcga_ha4 #dinov2_p_tcgaunn2 #dino_tcga_10tile_100_wOrg #dino_10tile_100, dino_tcga_10tile_100, dino_tcga_10tile_100_wOrg
ep20: False #Must be changed in cross_validation.py !!!
multi_dataset_analysis: True
single_d: train  # std=test. alt: train.
training_datasets: 
  - UNN_LUSC #- UNN_NSCLC
  - S36_LUSC #- S36_NSCLC
  #- NLST_LUSC
  
features_root_dir: /home/vilde/data/
#features_root_dir: /home/vilde/code/Phikon
#logs_root_dir: /home/vilde/code/Phikon/HistoSSLscaling/logs_2
logs_root_dir: /home/vilde/code/Phikon/HistoSSLscaling/logs_dataset